version: '3'
services: 
  admin:
    container_name: annat-admin
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports: 
      - '5000:5000'
